### ISSUE TITLE
/books/show画面のエラー(developmentブランチ)

### ISSUE THREAD

**Issue by hide9138** [hide9138/team06#35]
![スクリーンショット 2022-06-27 0 10 45](https://user-images.githubusercontent.com/59064540/175820877-8463ab47-ff4c-4e11-89d0-9daa3b5027f7.png)

**Comment by s-yukisato** [comment]
すぐに修正します

**Comment by s-yukisato** [comment]
ごめんなさい！
関係ありそうなところはすべて修正したと思っていたら忘れてました...

- サイドバー (sidebar component)
- 書籍検索結果一覧 (bookSearch component)
を持つページ（pages/**/*.js）は以下のような記述が必要になります

※「Home」の部分は export するコンポーネントの名前が入ります

<img width="430" alt="スクリーンショット 2022-06-27 7 33 24" src="https://user-images.githubusercontent.com/83949146/175836281-a374712a-6a7d-4c3b-a09a-acd6cf3fd6e6.png">

**Comment by hide9138** [comment]
close #37 
developmentの全体チェックをしていてファイルの中身をあまり見れてなかったです🙏
早急な対応ありがとうございます！
