### ISSUE TITLE
figmaをreactに書き出し

### ISSUE THREAD

**Issue by hide9138** [hide9138/team06#5]
# figma to reactかAWS amplifyを使って書き出しをする

@s-yukisato

**Comment by s-yukisato** [comment]
比較検討してみる

- [ ] figma to react plugin
- [ ] Amplify

**Comment by s-yukisato** [comment]
- [ ] 本の詳細画面

- [ ] アウトプット画面

- [ ] プロフィール画面

**Comment by s-yukisato** [comment]
- [ ] 3ワードツイート画面（画面2）books/new2
- [ ] 3ワードツイート画面（画面1） books/new1
