### ISSUE TITLE
プロフィール画面に遷移する際エラーが発生

### ISSUE THREAD

**Issue by komei0727** [hide9138/team06#54]
ブランチ: Development
```
Unhandled Runtime Error
Error: Image is missing required "src" property. Make sure you pass "src" in props to the `next/image` component. Received: {"width":"135","height":"182"}
```

**Comment by hide9138** [comment]
@komei0727 
こちらでエラーの確認はできていないです。
プロフィール画像のリンクが取得できてないかそもそもDBにないのかだと思います。
別アカかもう一回試してみてください。
![スクリーンショット 2022-06-29 10 51 20](https://user-images.githubusercontent.com/59064540/176333895-9afeaa7f-8e97-4e65-9d94-3e300520daf9.png)

**Comment by hide9138** [comment]
@komei0727 
これって結局大丈夫でした？
