### ISSUE TITLE
本の検索機能

### ISSUE THREAD

**Issue by hide9138** [hide9138/team06#67]
@komei0727 
こちらいつ頃できそうです？
自分のserchBookなどは作り直して大丈夫ですよー

**Comment by hide9138** [comment]
# 検索機能
- [ ] 検索機能をnew1画面からモーダルで表示させる

**Comment by hide9138** [comment]
@komei0727 @s-yukisato 
先ほどのheightの部分ですが、自分だけこんな感じになっていますが、他の方は大丈夫そうですか？（本番環境でも同様）
![スクリーンショット 2022-07-01 11 34 04](https://user-images.githubusercontent.com/59064540/176812181-e3da303c-b376-4822-bb47-46989a94c546.png)

**Comment by s-yukisato** [comment]
すみません
僕の環境でも同様にそうなりました

確認して修正しておきます

**Comment by s-yukisato** [comment]
先ほどの修正は、僕の環境では検索結果をスクロールしたときに背景が途切れて見えていたので、そこを修正しました。
<img width="360" alt="スクリーンショット 2022-07-01 9 40 30" src="https://user-images.githubusercontent.com/83949146/176815802-1c890d0f-3c0d-49e1-85a6-3c7949ef2382.png">

未検索の場合のチェックはできていませんでした。ご報告ありがとうございます！
